spring:
  application:
    name: api-gateway

  security:
    oauth2:

      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: flow-manager
              uri: lb://flow-manager
              predicates:
                - Path=/api/v1/files/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}